### PR TITLE
Add support for specific minor version of the API.

### PR DESCRIPTION
**Pull request by kevynb**
pickup from where #22 was left

### CODE REVIEW

**Comment by kevynb** [comment]
@thgreasi do you think you will have some time this week to review the changes?

**Comment by thgreasi** [comment]
I'm sorry this takes so long, I will do my best to do it this week.

**Comment by kevynb** [comment]
No problem! Thank you

**Comment by thgreasi** [comment]
@umayr Can we release the current master as v2.5.0 please?

**Comment by umayr** [comment]
@thgreasi I have added you as an owner for this package. You can also publish releases now.

**Comment by thgreasi** [comment]
@umayr Cool thanks! 👍

**Pull request merged**
