### PR TITLE
Correct docs for invoice.exportPdf

### PR DESCRIPTION
**Pull request by robwalkerco**

### CODE REVIEW

**Comment by thgreasi** [comment]
Actually, there is also #37. How about updating README for that PR instead? I will try to publish during the weekend.

**Comment by thgreasi** [comment]
@robwalkerco #37 was just merged and adds the `retrievePdf` method, would it make sense to update this PR or would it be more appropriate to close it?

**Comment by robwalkerco** [comment]
This can be closed now then.

**Comment by thgreasi** [comment]
Thanks for finding the issue, bringing this up and PRing the fix :+1:

**Pull request closed without merging**
